# R for travis: see documentation at https://docs.travis-ci.com/user/languages/r

language: r
sudo: required
cache: packages

before_install:                                                         # copy-pasted from the ranger .travis.yml, as is the only package which requires c++11
  - sudo add-apt-repository -y ppa:ubuntu-toolchain-r/test -y
  - sudo apt-get -qq update
  - sudo apt-get -qq install gcc-4.8
  - sudo apt-get -qq install g++-4.8
  - sudo update-alternatives --install /usr/bin/gcc gcc /usr/bin/gcc-4.8 90
  - sudo update-alternatives --install /usr/bin/g++ g++ /usr/bin/g++-4.8 90
  - sudo update-alternatives --install /usr/bin/gcov gcov /usr/bin/gcov-4.8 90

install:
  - Rscript -e 'install.packages(c("devtools","roxygen2","testthat", "doMC", "dplyr", "glmnet", "ranger", "covr"))'
  - Rscript -e 'devtools::install_version("xgboost", version = "0.4-4", repos = "http://cran.us.r-project.org")'       # install older version of xgboost
  
after_success:
  - Rscript -e 'covr::codecov(quiet = FALSE)'
  
warnings_are_errors: false

notifications:
  email:
    on_success: change
    on_failure: change
