# R for travis: see documentation at https://docs.travis-ci.com/user/languages/r

language: r
sudo: required
cache: packages


install:
  - Rscript -e "install.packages(c( 'doMC', 'dplyr', 'glmnet', 'ranger', 'xgboost', 'Matrix', 'magrittr', 'utils', 'stats', 'graphics', 'grDevices', 'rlang', 'testthat', 'covr', 'remotes' ), repos =  'https://cloud.r-project.org/' )"
  

after_success:
  - Rscript -e 'covr::codecov(quiet = FALSE)'
  

warnings_are_errors: false

notifications:
  email:
    on_success: change
    on_failure: change
